### ISSUE TITLE
Improve the update checker

### ISSUE THREAD

**Issue by Pjoottr** [Lenny-del/TrunkControl#19]
The update checker can be made faster and better maintainable by doing the following change's

- Store all versions in the `System.Version` class instead of the `string` class
- Compare the version using the class, so when you are developing you won't get that annoying update is available pop-up
- Use the variable `latestVersionuri` so the lines don't get too long
- Remove the update checker variables in EntryPoint.cs

**Comment by Lenny-del** [comment]
> The update checker can be made faster and better maintainable by doing the following change's
> 
> 

- [ ] * Store all versions in the `System.Version` class instead of the `string` class
- [ ]  Compare the version using the class, so when you are developing you won't get that annoying update is available pop-up
- [x] Use the variable `latestVersionuri` so the lines don't get too long
- [x]  Remove the update checker variables in EntryPoint.cs

**Comment by Lenny-del** [comment]
Can you please elaborate on the remaining two potential changes?

**Comment by Lenny-del** [comment]
The update checker has been revamped and finalised. It's working sufficient in it's current state. Thanks to @Charlie-686 for suggesting new ideas.
